WIP

diff --git a/scripts/dev-start-client b/scripts/dev-start-client
--- a/scripts/dev-start-client
+++ b/scripts/dev-start-client
@@ -15,38 +15,12 @@ else
   exit 1
 fi
 
-
-# ⛄ npx parcel help serve
-# Usage: parcel serve [options] [input...]
-
-# starts a development server
-
-# Options:
-#   --public-url <url>         the path prefix for absolute urls
-#   --open [browser]           automatically open in specified browser, defaults to default browser
-#   --watch-for-stdin          exit when stdin closes
-#   --lazy                     Build async bundles on demand, when requested in the browser
-#   --no-hmr                   disable hot module replacement
-#   -p, --port <port>          set the port to serve on. defaults to $PORT or 1234
-#   --host <host>              set the host to listen on, defaults to listening on all interfaces
-#   --https                    serves files over HTTPS
-#   --cert <path>              path to certificate to use with HTTPS
-#   --key <path>               path to private key to use with HTTPS
-#   --hmr-port <port>          hot module replacement port
-#   --hmr-host <host>          hot module replacement host
-#   --no-cache                 disable the filesystem cache
-#   --config <path>            specify which config to use. can be a path or a package name
-#   --cache-dir <path>         set the cache directory. defaults to ".parcel-cache"
-#   --no-source-maps           disable sourcemaps
-#   --target [name]            only build given target(s) (default: [])
-#   --log-level <level>        set the log level (choices: "none", "error", "warn", "info", "verbose")
-#   --dist-dir <dir>           output directory to write to when unspecified by targets
-#   --no-autoinstall           disable autoinstall
-#   --profile                  enable build profiling
-#   -V, --version              output the version number
-#   --detailed-report [count]  print the asset timings and sizes in the build report
-#   --reporter <name>          additional reporters to run (default: [])
-#   -h, --help                 display help for command
+if [ -z "$SERVER_URL" ]; then
+  echo "ERROR: \$SERVER_URL is not set" 1>&2
+  exit 1
+else
+  echo SERVER_URL=${SERVER_URL}
+fi
 
 PORT=$(dotenv -e ${APP_PATH}/.env -p PORT)
 echo PORT=${PORT}
@@ -58,7 +32,6 @@ cat > "${APP_ROOT}/.proxyrc" <<-EOF
   }
 }
 EOF
-
 
 npx parcel serve \
   --port ${PORT} \
